/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConsentInviteRouteImport } from './routes/consent-invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as WaitingRouteImport } from './routes/waiting'
import { Route as ProfilesProfileIdRouteImport } from './routes/profiles.$profileId'
import { Route as ProfilesNewRouteImport } from './routes/profiles.new'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewDocumentIdRouteImport } from './routes/review.$documentId'
import { Route as ProfilesProfileIdManualRouteImport } from './routes/profiles.$profileId_.manual'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentInviteRoute = ConsentInviteRouteImport.update({
  id: '/consent-invite',
  path: '/consent-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesProfileIdRoute = ProfilesProfileIdRouteImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesNewRoute = ProfilesNewRouteImport.update({
  id: '/profiles/new',
  path: '/profiles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewDocumentIdRoute = ReviewDocumentIdRouteImport.update({
  id: '/review/$documentId',
  path: '/review/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesProfileIdManualRoute = ProfilesProfileIdManualRouteImport.update({
  id: '/profiles/$profileId_/manual',
  path: '/profiles/$profileId/manual',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consent-invite': typeof ConsentInviteRoute
  '/login': typeof LoginRoute
  '/upload': typeof UploadRoute
  '/waiting': typeof WaitingRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/review/$documentId': typeof ReviewDocumentIdRoute
  '/review/': typeof ReviewIndexRoute
  '/profiles/$profileId/manual': typeof ProfilesProfileIdManualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consent-invite': typeof ConsentInviteRoute
  '/login': typeof LoginRoute
  '/upload': typeof UploadRoute
  '/waiting': typeof WaitingRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/review/$documentId': typeof ReviewDocumentIdRoute
  '/review': typeof ReviewIndexRoute
  '/profiles/$profileId/manual': typeof ProfilesProfileIdManualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consent-invite': typeof ConsentInviteRoute
  '/login': typeof LoginRoute
  '/upload': typeof UploadRoute
  '/waiting': typeof WaitingRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/review/$documentId': typeof ReviewDocumentIdRoute
  '/review/': typeof ReviewIndexRoute
  '/profiles/$profileId_/manual': typeof ProfilesProfileIdManualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consent-invite'
    | '/login'
    | '/upload'
    | '/waiting'
    | '/profiles/$profileId'
    | '/profiles/new'
    | '/review/$documentId'
    | '/review/'
    | '/profiles/$profileId/manual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/consent-invite'
    | '/login'
    | '/upload'
    | '/waiting'
    | '/profiles/$profileId'
    | '/profiles/new'
    | '/review/$documentId'
    | '/review'
    | '/profiles/$profileId/manual'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consent-invite'
    | '/login'
    | '/upload'
    | '/waiting'
    | '/profiles/$profileId'
    | '/profiles/new'
    | '/review/$documentId'
    | '/review/'
    | '/profiles/$profileId_/manual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConsentInviteRoute: typeof ConsentInviteRoute
  LoginRoute: typeof LoginRoute
  UploadRoute: typeof UploadRoute
  WaitingRoute: typeof WaitingRoute
  ProfilesProfileIdRoute: typeof ProfilesProfileIdRoute
  ProfilesNewRoute: typeof ProfilesNewRoute
  ReviewDocumentIdRoute: typeof ReviewDocumentIdRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  ProfilesProfileIdManualRoute: typeof ProfilesProfileIdManualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent-invite': {
      id: '/consent-invite'
      path: '/consent-invite'
      fullPath: '/consent-invite'
      preLoaderRoute: typeof ConsentInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$profileId': {
      id: '/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof ProfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/new': {
      id: '/profiles/new'
      path: '/profiles/new'
      fullPath: '/profiles/new'
      preLoaderRoute: typeof ProfilesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$documentId': {
      id: '/review/$documentId'
      path: '/review/$documentId'
      fullPath: '/review/$documentId'
      preLoaderRoute: typeof ReviewDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$profileId_/manual': {
      id: '/profiles/$profileId_/manual'
      path: '/profiles/$profileId/manual'
      fullPath: '/profiles/$profileId/manual'
      preLoaderRoute: typeof ProfilesProfileIdManualRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConsentInviteRoute: ConsentInviteRoute,
  LoginRoute: LoginRoute,
  UploadRoute: UploadRoute,
  WaitingRoute: WaitingRoute,
  ProfilesProfileIdRoute: ProfilesProfileIdRoute,
  ProfilesNewRoute: ProfilesNewRoute,
  ReviewDocumentIdRoute: ReviewDocumentIdRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  ProfilesProfileIdManualRoute: ProfilesProfileIdManualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
