/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Kiểm tra sức khỏe hệ thống (DB + storage) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Mọi phụ thuộc hoạt động */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
        /** @description Ít nhất một phụ thuộc không phản hồi */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chuyển hướng sang Authentik (OIDC Code + PKCE S256) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Chuyển hướng */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Nhận code từ Authentik, tạo phiên và đặt cookie angia_session */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Chuyển hướng */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Hủy phiên hiện hành (cần X-CSRF-Token) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Đã xóa phiên và cookie angia_session */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: thiếu hoặc sai X-CSRF-Token */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ngữ cảnh tài khoản, nhóm, vai trò và CSRF token của phiên hiện hành */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Phiên còn hạn; family/role null khi tài khoản chờ gán nhóm */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MeContextResponse'];
          };
        };
        /** @description ERR_UNAUTHENTICATED: thiếu phiên, phiên hết hạn hoặc cookie không hợp lệ */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/families': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Danh sách nhóm gia đình */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Mọi nhóm, cũ nhất trước */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Family'][];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: không phải Quản trị hệ thống hoặc thiếu/sai X-CSRF-Token */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /** Khởi tạo nhóm gia đình mới (SPEC-001) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateFamilyRequest'];
        };
      };
      responses: {
        /** @description Nhóm mới, chưa có tài khoản nào */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Family'];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: không phải Quản trị hệ thống hoặc thiếu/sai X-CSRF-Token */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_VALIDATION: tên rỗng hoặc dài hơn 60 ký tự */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Danh sách tài khoản kèm nhóm và vai trò, gồm tài khoản chờ gán nhóm */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Mọi tài khoản, cũ nhất trước */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Account'][];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: không phải Quản trị hệ thống hoặc thiếu/sai X-CSRF-Token */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/accounts/{id}/membership': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Phân bổ tài khoản vào nhóm và vai trò (SPEC-002) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AssignMembershipRequest'];
        };
      };
      responses: {
        /** @description Tài khoản sau khi gán */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Account'];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: không phải Quản trị hệ thống hoặc thiếu/sai X-CSRF-Token */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND: tài khoản hoặc nhóm không tồn tại */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_ACCOUNT_ALREADY_IN_FAMILY | ERR_FIRST_ACCOUNT_MUST_BE_MAIN */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_VALIDATION */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    /** Điều chỉnh vai trò hoặc gỡ tài khoản khỏi nhóm (SPEC-003) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ChangeMembershipRequest'];
        };
      };
      responses: {
        /** @description Tài khoản sau thay đổi; gỡ khỏi nhóm thì familyId/role null (chờ gán nhóm) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Account'];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: không phải Quản trị hệ thống hoặc thiếu/sai X-CSRF-Token */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND: tài khoản không tồn tại hoặc chưa thuộc nhóm nào */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_LAST_MAIN */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_VALIDATION */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/health-profiles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Hồ sơ của gia đình hiện tại */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Hồ sơ, cũ nhất trước */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthProfile'][];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: cần main cùng gia đình và CSRF cho request ghi */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /** Tạo hồ sơ chưa xác nhận đồng thuận */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateHealthProfileRequest'];
        };
      };
      responses: {
        /** @description Hồ sơ đã tạo */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthProfile'];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: cần main cùng gia đình và CSRF cho request ghi */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND: tài khoản không thuộc nhóm */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_PROFILE_ALREADY_LINKED */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_VALIDATION: tên/năm sinh/tài khoản không hợp lệ */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health-profiles/linkable-accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tài khoản cùng gia đình chưa liên kết hồ sơ */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Tài khoản có thể liên kết */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LinkableAccount'][];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: cần main cùng gia đình và CSRF cho request ghi */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health-profiles/{id}/consent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Route cũ: yêu cầu tạo link mời, không ghi đồng thuận */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ConfirmConsentRequest'];
        };
      };
      responses: {
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: cần main cùng gia đình và CSRF cho request ghi */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_CONSENT_INVITATION_REQUIRED */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_VALIDATION */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health-profiles/{id}/upload-batches': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tải lên 1–10 ảnh chứng từ (JPEG/PNG/HEIC/WebP ≤ 10 MiB/ảnh) cho hồ sơ đã đồng thuận */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': components['schemas']['UploadBatchRequest'];
        };
      };
      responses: {
        /** @description Lô tải lên: chứng từ hợp lệ trạng thái uploaded, tệp bị loại trong rejectedFiles */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UploadBatchResponse'];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: cần main cùng gia đình và CSRF */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND: hồ sơ không thuộc gia đình */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_CONSENT_REQUIRED */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_BATCH_TOO_LARGE: quá 10 tệp hoặc body vượt trần */
        413: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_VALIDATION (không có tệp, sai loại khai báo) hoặc ERR_NO_VALID_FILE */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_UPLOAD_BUSY: đã có 3 lô đang xử lý; thử lại sau số giây trong Retry-After */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/source-documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Danh sách chứng từ của gia đình theo bộ lọc, mới nhất trước; lọc theo lô thì theo ngày chứng từ tăng dần */
    get: {
      parameters: {
        query?: {
          status?:
            | (
                | 'uploaded'
                | 'extracting'
                | 'pending_review'
                | 'approved'
                | 'rejected'
                | 'manual_entry'
                | 'awaiting_budget'
              )
            | (
                | 'uploaded'
                | 'extracting'
                | 'pending_review'
                | 'approved'
                | 'rejected'
                | 'manual_entry'
                | 'awaiting_budget'
              )[];
          profileId?: string;
          batchId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Chứng từ */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SourceDocument'][];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: cần main cùng gia đình (và CSRF với lệnh đột biến) */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/source-documents/{id}/review': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chứng từ kèm bản trích xuất mới nhất để điền form đối soát */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dữ liệu duyệt */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DocumentReview'];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: cần main cùng gia đình (và CSRF với lệnh đột biến) */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/source-documents/{id}/image': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Luồng ảnh chứng từ (preview chưa có thì trả ảnh gốc) */
    get: {
      parameters: {
        query?: {
          variant?: 'preview' | 'original';
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ảnh */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'image/*': string;
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: cần main cùng gia đình (và CSRF với lệnh đột biến) */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/source-documents/{id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Phê duyệt bản trích xuất số đo máy (E2-S6-T1: chỉ device_reading) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApproveDocumentRequest'];
        };
      };
      responses: {
        /** @description Chứng từ approved và số đo đã lưu */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApprovedDocumentResponse'];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN: cần main cùng gia đình (và CSRF với lệnh đột biến) */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_INVALID_STATE_TRANSITION */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_DOCUMENT_DATE_REQUIRED, ERR_BP_INVALID, ERR_GLUCOSE_UNIT_REQUIRED, ERR_OUT_OF_RANGE_UNCONFIRMED (details.fields), ERR_VALIDATION */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health-profiles/{id}/measurements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Số đo sinh tồn đã duyệt của hồ sơ, mới nhất trước */
    get: {
      parameters: {
        query?: {
          kind?: 'blood_pressure' | 'glucose';
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Số đo */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Measurement'][];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND: hồ sơ không thuộc gia đình */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health-profiles/{id}/consent-invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Link mới, hết hạn sau 7 ngày */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConsentInvitationCreated'];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_CONSENT_ALREADY_CONFIRMED */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_VALIDATION */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Đã thu hồi link đang chờ */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConsentInvitationRevoked'];
          };
        };
        /** @description ERR_UNAUTHENTICATED */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_FORBIDDEN */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_CONSENT_ALREADY_CONFIRMED */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_VALIDATION */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consent-invitations/view': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Thông tin tối thiểu, không tiêu thụ token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConsentInvitationView'];
          };
        };
        /** @description ERR_NOT_FOUND */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/consent-invitations/respond': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ConsentInvitationRespondRequest'];
        };
      };
      responses: {
        /** @description Giữ quyết định và metadata phản hồi đầu */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConsentInvitationReceipt'];
          };
        };
        /** @description ERR_FORBIDDEN: Origin */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_NOT_FOUND */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ERR_VALIDATION */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponse: {
      /** @enum {string} */
      status: 'ok' | 'degraded';
      /** @enum {string} */
      db: 'ok' | 'down';
      /** @enum {string} */
      storage: 'ok' | 'down';
    };
    ErrorResponse: {
      error: {
        code: string;
        message: string;
        details?: {
          [key: string]: unknown;
        };
      };
    };
    MeContextResponse: {
      account: {
        /** Format: uuid */
        id: string;
        displayName: string;
        isSystemAdmin: boolean;
        /** Format: uuid */
        healthProfileId: string | null;
      };
      family: {
        /** Format: uuid */
        id: string;
        name: string;
      } | null;
      /** @enum {string|null} */
      role: 'main' | 'member' | null;
      csrfToken: string;
    };
    Family: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: date-time */
      createdAt: string;
    };
    CreateFamilyRequest: {
      name: string;
    };
    Account: {
      /** Format: uuid */
      id: string;
      displayName: string;
      isSystemAdmin: boolean;
      /** Format: uuid */
      familyId: string | null;
      /** @enum {string|null} */
      role: 'main' | 'member' | null;
    };
    AssignMembershipRequest: {
      /** Format: uuid */
      familyId: string;
      /** @enum {string} */
      role: 'main' | 'member';
    };
    ChangeMembershipRequest:
      | {
          /** @enum {string} */
          action: 'change_role';
          /** @enum {string} */
          role: 'main' | 'member';
        }
      | {
          /** @enum {string} */
          action: 'remove';
        };
    HealthProfile: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      familyId: string;
      displayName: string;
      birthYear: number | null;
      /** Format: date-time */
      consentConfirmedAt: string | null;
      /** Format: uuid */
      consentConfirmedBy: string | null;
      /** @enum {string|null} */
      consentBasis: 'self' | 'guardian' | null;
      /** @enum {string} */
      consentStatus: 'pending' | 'invited' | 'declined' | 'confirmed';
      /** @enum {string|null} */
      consentSource: 'legacy_attestation' | 'invitation' | null;
      consentRespondentName: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    LinkableAccount: {
      /** Format: uuid */
      id: string;
      displayName: string;
    };
    CreateHealthProfileRequest: {
      displayName: string;
      birthYear?: number;
      /** Format: uuid */
      linkedAccountId?: string;
    };
    ConfirmConsentRequest: {
      /** @enum {string} */
      confirmedBy: 'self' | 'guardian';
    };
    UploadBatchResponse: {
      /** Format: uuid */
      id: string;
      documents: components['schemas']['SourceDocument'][];
      rejectedFiles: {
        fileName: string;
        /** @enum {string} */
        code: 'ERR_UNSUPPORTED_FILE' | 'ERR_FILE_TOO_LARGE';
      }[];
    };
    SourceDocument: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      healthProfileId: string;
      /** Format: uuid */
      batchId: string;
      /** @enum {string|null} */
      type: 'prescription' | 'lab_result' | 'device_reading' | null;
      /** @enum {string} */
      status:
        | 'uploaded'
        | 'extracting'
        | 'pending_review'
        | 'approved'
        | 'rejected'
        | 'manual_entry'
        | 'awaiting_budget';
      /** Format: date */
      documentDate: string | null;
      mimeType: string;
      sizeBytes: number;
      /** Format: date-time */
      createdAt: string;
    };
    UploadBatchRequest: {
      files: string | string[];
      /** @enum {string} */
      declaredType?: 'prescription' | 'lab_result' | 'device_reading';
    };
    DocumentReview: {
      document: components['schemas']['SourceDocument'];
      extraction:
        | {
            /** @enum {string} */
            type: 'prescription';
            issuedDate: string | null;
            facility: string | null;
            items: {
              name: string;
              strength: string | null;
              quantityPerDose: number | null;
              doseUnit: string | null;
              slots: ('morning' | 'noon' | 'afternoon' | 'evening')[];
              durationDays: number | null;
              longTerm: boolean;
              note: string | null;
            }[];
          }
        | {
            /** @enum {string} */
            type: 'lab_result';
            resultDate: string | null;
            facility: string | null;
            items: {
              testName: string;
              value: string | null;
              unit: string | null;
              referenceRange: string | null;
            }[];
          }
        | {
            /** @enum {string} */
            type: 'device_reading';
            measuredAt: string | null;
            measuredTime: string | null;
            /** @enum {string} */
            kind: 'blood_pressure' | 'glucose';
            systolic: number | null;
            diastolic: number | null;
            pulse: number | null;
            glucoseValue: number | null;
            /** @enum {string|null} */
            glucoseUnit: 'mmol/L' | 'mg/dL' | null;
          }
        | null;
    };
    ApprovedDocumentResponse: {
      document: components['schemas']['SourceDocument'];
      measurements: components['schemas']['Measurement'][];
    };
    Measurement: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      healthProfileId: string;
      /** Format: uuid */
      sourceDocumentId: string | null;
      /** @enum {string} */
      kind: 'blood_pressure' | 'glucose';
      /** Format: date */
      measuredOn: string;
      measuredTime: string | null;
      systolic: number | null;
      diastolic: number | null;
      pulse: number | null;
      glucoseValue: number | null;
      /** @enum {string|null} */
      glucoseUnit: 'mmol/L' | 'mg/dL' | null;
      manualWithoutSource: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    ApproveDocumentRequest: {
      /** @enum {string} */
      type: 'device_reading';
      data: {
        /** @enum {string} */
        type: 'device_reading';
        /** Format: date */
        measuredAt: string | null;
        measuredTime: string | null;
        /** @enum {string} */
        kind: 'blood_pressure' | 'glucose';
        systolic: number | null;
        diastolic: number | null;
        pulse: number | null;
        glucoseValue: number | null;
        /** @enum {string|null} */
        glucoseUnit: 'mmol/L' | 'mg/dL' | null;
      };
      confirmOutOfRange?: boolean;
    };
    ConsentInvitationCreated: {
      token: string;
      /** Format: date-time */
      expiresAt: string;
    };
    ConsentInvitationRevoked: {
      /** @enum {string} */
      status: 'pending';
    };
    ConsentInvitationView: {
      profileDisplayName: string;
      inviterDisplayName: string | null;
      /** Format: date-time */
      expiresAt: string;
      /** @enum {string} */
      status: 'pending' | 'accepted' | 'declined';
    };
    ConsentInvitationReceipt: {
      /** @enum {string} */
      outcome: 'recorded' | 'already_responded';
      /** @enum {string} */
      decision: 'accepted' | 'declined';
      respondentName: string;
      /** @enum {string} */
      basis: 'self' | 'guardian';
      /** Format: date-time */
      respondedAt: string;
    };
    ConsentInvitationRespondRequest: {
      respondentName: string;
      /** @enum {string} */
      basis: 'self' | 'guardian';
      /** @enum {string} */
      decision: 'accepted' | 'declined';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
